// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddROMFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddROMFiles'](arg1, arg2, arg3);
}

export function AddStorageUnit() {
  return window['go']['main']['App']['AddStorageUnit']();
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CheckMediaItemsUpdate() {
  return window['go']['main']['App']['CheckMediaItemsUpdate']();
}

export function CleanBuildDir(arg1) {
  return window['go']['main']['App']['CleanBuildDir'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function GetActiveInstall() {
  return window['go']['main']['App']['GetActiveInstall']();
}

export function GetCatalogActivity() {
  return window['go']['main']['App']['GetCatalogActivity']();
}

export function GetCatalogInfo() {
  return window['go']['main']['App']['GetCatalogInfo']();
}

export function GetGames() {
  return window['go']['main']['App']['GetGames']();
}

export function GetInstallPrompts(arg1) {
  return window['go']['main']['App']['GetInstallPrompts'](arg1);
}

export function GetInstallSize(arg1) {
  return window['go']['main']['App']['GetInstallSize'](arg1);
}

export function GetInstallState(arg1) {
  return window['go']['main']['App']['GetInstallState'](arg1);
}

export function GetItemUpdate(arg1) {
  return window['go']['main']['App']['GetItemUpdate'](arg1);
}

export function GetLibraryStatus() {
  return window['go']['main']['App']['GetLibraryStatus']();
}

export function GetLibraryStorage() {
  return window['go']['main']['App']['GetLibraryStorage']();
}

export function GetMediaItemsSHA() {
  return window['go']['main']['App']['GetMediaItemsSHA']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetROMLibrary() {
  return window['go']['main']['App']['GetROMLibrary']();
}

export function GetROMStatus(arg1) {
  return window['go']['main']['App']['GetROMStatus'](arg1);
}

export function GetSaveLinks(arg1) {
  return window['go']['main']['App']['GetSaveLinks'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSpecVersions(arg1) {
  return window['go']['main']['App']['GetSpecVersions'](arg1);
}

export function GetStorageUnits() {
  return window['go']['main']['App']['GetStorageUnits']();
}

export function GetVersion(arg1) {
  return window['go']['main']['App']['GetVersion'](arg1);
}

export function GetVersions() {
  return window['go']['main']['App']['GetVersions']();
}

export function ImportROMs(arg1, arg2) {
  return window['go']['main']['App']['ImportROMs'](arg1, arg2);
}

export function InstallVersion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['InstallVersion'](arg1, arg2, arg3, arg4);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function LaunchVersion(arg1, arg2) {
  return window['go']['main']['App']['LaunchVersion'](arg1, arg2);
}

export function MatchDroppedROMs(arg1) {
  return window['go']['main']['App']['MatchDroppedROMs'](arg1);
}

export function OpenStorageUnit(arg1) {
  return window['go']['main']['App']['OpenStorageUnit'](arg1);
}

export function RefreshLibraryIndex() {
  return window['go']['main']['App']['RefreshLibraryIndex']();
}

export function RemoveStorageUnit(arg1) {
  return window['go']['main']['App']['RemoveStorageUnit'](arg1);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function RenameStorageUnit(arg1, arg2) {
  return window['go']['main']['App']['RenameStorageUnit'](arg1, arg2);
}

export function ReorderStorageUnits(arg1) {
  return window['go']['main']['App']['ReorderStorageUnits'](arg1);
}

export function RevealSaves(arg1) {
  return window['go']['main']['App']['RevealSaves'](arg1);
}

export function SelectROMFiles() {
  return window['go']['main']['App']['SelectROMFiles']();
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function SetAutoRefreshCatalog(arg1) {
  return window['go']['main']['App']['SetAutoRefreshCatalog'](arg1);
}

export function SyncMediaItems() {
  return window['go']['main']['App']['SyncMediaItems']();
}

export function UninstallVersion(arg1) {
  return window['go']['main']['App']['UninstallVersion'](arg1);
}

export function UpdateMediaItem(arg1) {
  return window['go']['main']['App']['UpdateMediaItem'](arg1);
}

export function ValidateMediaItemsPath() {
  return window['go']['main']['App']['ValidateMediaItemsPath']();
}
