// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storageunit} from '../models';
import {main} from '../models';
import {models} from '../models';
import {engine} from '../models';

export function AddROMFiles(arg1:string,arg2:Array<string>,arg3:boolean):Promise<Array<string>>;

export function AddStorageUnit():Promise<storageunit.StorageUnit>;

export function CancelInstall():Promise<void>;

export function CheckMediaItemsUpdate():Promise<boolean>;

export function CleanBuildDir(arg1:string):Promise<void>;

export function GetActiveInstall():Promise<string>;

export function GetCatalogInfo():Promise<main.CatalogInfo>;

export function GetGames():Promise<Array<models.VideoGame>>;

export function GetInstallPrompts(arg1:string):Promise<Array<models.ArgPrompt>>;

export function GetInstallSize(arg1:string):Promise<number>;

export function GetInstallState(arg1:string):Promise<models.InstallState>;

export function GetItemUpdate(arg1:string):Promise<boolean>;

export function GetLibraryStatus():Promise<Record<string, main.LibraryStatus>>;

export function GetLibraryStorage():Promise<main.LibraryStorage>;

export function GetMediaItemsSHA():Promise<string>;

export function GetPlatform():Promise<string>;

export function GetROMLibrary():Promise<models.ROMLibrary>;

export function GetROMStatus(arg1:string):Promise<Record<string, boolean>>;

export function GetSettings():Promise<main.Settings>;

export function GetSpecVersions(arg1:string):Promise<Array<engine.SpecVersion>>;

export function GetStorageUnits():Promise<Array<storageunit.StorageUnit>>;

export function GetVersion(arg1:string):Promise<models.VideoGameVersion>;

export function GetVersions():Promise<Array<models.VideoGameVersion>>;

export function ImportROMs(arg1:Array<models.ROMFileMatch>,arg2:boolean):Promise<void>;

export function InstallVersion(arg1:string,arg2:Record<string, string>,arg3:string,arg4:string):Promise<void>;

export function IsDevMode():Promise<boolean>;

export function LaunchVersion(arg1:string,arg2:string):Promise<void>;

export function MatchDroppedROMs(arg1:Array<string>):Promise<models.ROMDropSummary>;

export function OpenStorageUnit(arg1:string):Promise<void>;

export function RefreshLibraryIndex():Promise<void>;

export function RemoveStorageUnit(arg1:string):Promise<void>;

export function RenameStorageUnit(arg1:string,arg2:string):Promise<void>;

export function ReorderStorageUnits(arg1:Array<string>):Promise<void>;

export function SetAutoRefreshCatalog(arg1:boolean):Promise<void>;

export function SelectROMFiles():Promise<Array<string>>;

export function SyncMediaItems():Promise<void>;

export function UninstallVersion(arg1:string):Promise<void>;

export function UpdateMediaItem(arg1:string):Promise<void>;

export function ValidateMediaItemsPath():Promise<string>;
